#include "constants.h"


/* VALUES INITIALISATION */

// MARKER ID
const int CONSTANTS::ARTAG_ID = 209192064;

// EDGELS DETECTION PARAMETERS
CONST int CONSTANTS::REGION_PIXEL_SIZE = 60;
CONST int CONSTANTS::SCANLINE_STRIDE = 5;
CONST std::vector<int> CONSTANTS::FILTER = { -1, 0, 1 };
CONST int CONSTANTS::INTENSITY_THRESHOLD = 45;
CONST int CONSTANTS::CHANNEL_GAP_THRESHOLD = 20;

// RANSAC GROUPER PARAMETERS
CONST float CONSTANTS::ORIENTATION_TOLERANCE = M_PI / 4;
CONST int CONSTANTS::HYPOLINE_ATTEMPTS = 30;
CONST float CONSTANTS::POINT_LINE_DIST_TOLERANCE = 0.3f;
CONST int CONSTANTS::DOMINANT_LINE_SEARCH_ATTEMPTS = 20;
CONST int CONSTANTS::MIN_DOMINANT_LINE_VOTES = 2;
CONST int CONSTANTS::MAX_LINE_SEARCH_ITER = 4;